// Code generated by "stringer -type=LogFormat"; DO NOT EDIT

package slogging

import "fmt"

const _LogFormat_name = "JSONELFStandard"

var _LogFormat_index = [...]uint8{0, 4, 7, 15}

func (i LogFormat) String() string {
	i -= 1
	if i < 0 || i >= LogFormat(len(_LogFormat_index)-1) {
		return fmt.Sprintf("LogFormat(%d)", i+1)
	}
	return _LogFormat_name[_LogFormat_index[i]:_LogFormat_index[i+1]]
}
