// Code generated by "stringer -type=LogFormat"; DO NOT EDIT.

package logging

import "strconv"

const _LogFormat_name = "JSONELFStandard"

var _LogFormat_index = [...]uint8{0, 4, 7, 15}

func (i LogFormat) String() string {
	i -= 1
	if i < 0 || i >= LogFormat(len(_LogFormat_index)-1) {
		return "LogFormat(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _LogFormat_name[_LogFormat_index[i]:_LogFormat_index[i+1]]
}
