// Code generated by "stringer -type=LogLevel"; DO NOT EDIT

package slogging

import "fmt"

const _LogLevel_name = "ERRORWARNINFODEBUG"

var _LogLevel_index = [...]uint8{0, 5, 9, 13, 18}

func (i LogLevel) String() string {
	i -= 1
	if i < 0 || i >= LogLevel(len(_LogLevel_index)-1) {
		return fmt.Sprintf("LogLevel(%d)", i+1)
	}
	return _LogLevel_name[_LogLevel_index[i]:_LogLevel_index[i+1]]
}
